clouds=off
sky=false
sun=false
moon=false
stars=false
oldLighting=false
program.shadow.enabled=SHADOWS
shadowTranslucent=false
underwaterOverlay=false
vignette=false

screen=<profile> [ATMOSPHERE] [LIGHT] [SURFACE] [POST]
screen.ATMOSPHERE=CLOUDS CLOUD_DENSITY FOG_DENSITY
screen.LIGHT=SHADOWS SHADOW_SAMPLES shadowMapResolution shadowDistance
screen.SURFACE=WIND_STRENGTH
screen.POST=BLOOM_STRENGTH OUTLINE_STRENGTH SATURATION

profile.LOW=!CLOUDS !SHADOWS !program.shadow SHADOW_SAMPLES:4 shadowMapResolution:1024 BLOOM_STRENGTH:0.0 OUTLINE_STRENGTH:0.0
profile.BALANCED=CLOUDS CLOUD_DENSITY:0.48 SHADOWS program.shadow SHADOW_SAMPLES:4 shadowMapResolution:1024 BLOOM_STRENGTH:0.1 OUTLINE_STRENGTH:0.14
profile.HIGH=CLOUDS CLOUD_DENSITY:0.48 SHADOWS program.shadow SHADOW_SAMPLES:9 shadowMapResolution:2048 BLOOM_STRENGTH:0.18 OUTLINE_STRENGTH:0.14

sliders=CLOUD_DENSITY FOG_DENSITY BLOOM_STRENGTH OUTLINE_STRENGTH WIND_STRENGTH SATURATION shadowDistance





