# Asterweave shader pack settings
shadowMapResolution=2048
shadowDistance=160
shadowHardwareFiltering=false
colortex0Format=RGBA16F
colortex1Format=RGBA16F
colortex2Format=RGBA16F
sliders=AW_BLOOM_STRENGTH AW_ATMOSPHERE AW_CHROMATIC_EDGE AW_GRAIN
