"""Generate only thin Iris entry points. Visual implementations live in shaders/program.
No downloaded templates, libraries or existing shaderpacks are used.
"""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PROGRAMS = {
    'gbuffers_basic': ('geometry', ['GEOM_UNTEXTURED', 'GEOM_UNLIT']),
    'gbuffers_line': ('geometry', ['GEOM_UNTEXTURED', 'GEOM_UNLIT', 'GEOM_TRANSLUCENT']),
    'gbuffers_textured': ('geometry', []),
    'gbuffers_textured_lit': ('geometry', []),
    'gbuffers_particles': ('geometry', []),
    'gbuffers_particles_translucent': ('geometry', ['GEOM_TRANSLUCENT', 'GEOM_FORWARD']),
    'gbuffers_terrain': ('geometry', ['GEOM_TERRAIN']),
    'gbuffers_block': ('geometry', ['GEOM_ENTITY']),
    'gbuffers_block_translucent': ('geometry', ['GEOM_ENTITY', 'GEOM_TRANSLUCENT', 'GEOM_FORWARD']),
    'gbuffers_entities': ('geometry', ['GEOM_ENTITY']),
    'gbuffers_entities_translucent': ('geometry', ['GEOM_ENTITY', 'GEOM_TRANSLUCENT', 'GEOM_FORWARD']),
    'gbuffers_hand': ('geometry', ['GEOM_HAND']),
    'gbuffers_hand_water': ('geometry', ['GEOM_HAND', 'GEOM_TRANSLUCENT', 'GEOM_FORWARD']),
    'gbuffers_water': ('water', ['GEOM_WATER', 'GEOM_TRANSLUCENT']),
    'gbuffers_weather': ('geometry', ['GEOM_TRANSLUCENT', 'GEOM_FORWARD']),
    'gbuffers_damagedblock': ('geometry', ['GEOM_UNLIT', 'GEOM_TRANSLUCENT']),
    'gbuffers_armor_glint': ('geometry', ['GEOM_EMISSIVE', 'GEOM_TRANSLUCENT']),
    'gbuffers_spidereyes': ('geometry', ['GEOM_ENTITY', 'GEOM_EMISSIVE', 'GEOM_TRANSLUCENT']),
    'gbuffers_beaconbeam': ('geometry', ['GEOM_EMISSIVE', 'GEOM_TRANSLUCENT']),
    'gbuffers_lightning': ('geometry', ['GEOM_UNTEXTURED', 'GEOM_EMISSIVE', 'GEOM_TRANSLUCENT']),
    'gbuffers_skybasic': ('sky', []),
    'gbuffers_skytextured': ('sky', []),
    'gbuffers_clouds': ('sky', []),
    'shadow': ('shadow', []),
    'prepare': ('prepare', []),
    'deferred': ('deferred', []),
    'composite': ('composite', []),
    'composite1': ('resolve', []),
    'composite2': ('bloom_extract', []),
    'composite3': ('blur', ['BLUR_HORIZONTAL']),
    'composite4': ('blur', []),
    'composite5': ('tonemap', []),
    'final': ('final', []),
}
FULLSCREEN = {'prepare', 'deferred', 'composite', 'resolve', 'bloom_extract', 'blur', 'tonemap', 'final'}
def generate():
    count = 0
    # Legacy dimension paths are part of the Iris shaderpack API. Root is a safe
    # Overworld-style fallback for dimensions without an explicit assignment.
    for folder, dimension in [('', 0), ('world0', 0), ('world-1', -1), ('world1', 1)]:
        target = ROOT/'shaders'/folder
        target.mkdir(parents=True, exist_ok=True)
        for name, (source, flags) in PROGRAMS.items():
            for extension in ['vsh','fsh']:
                implementation = source
                if extension == 'vsh':
                    if source in FULLSCREEN: implementation = 'fullscreen'
                    if source == 'water': implementation = 'geometry'
                text = '#version 330 compatibility\n// Original Tidelume entry point; generated by tools/generate_programs.py.\n'
                text += f'#define WORLD_KIND {dimension}\n'
                text += ''.join(f'#define {flag}\n' for flag in flags)
                text += f'#include "/program/{implementation}.{extension}"\n'
                (target/f'{name}.{extension}').write_text(text,encoding='utf-8',newline='\n')
                count += 1
    print(f'Generated {count} entry points ({len(PROGRAMS)} program pairs x 4 dimension paths).')
if __name__ == '__main__': generate()
