#version 330 compatibility
// Original Tidelume entry point; generated by tools/generate_programs.py.
#define WORLD_KIND 0
#define GEOM_ENTITY
#define GEOM_TRANSLUCENT
#define GEOM_FORWARD
#include "/program/geometry.vsh"
