# 雾棱山晓管线配置
shadowMapResolution = 2048
shadowDistance = 160.0
sunPathRotation = -15.0
ambientOcclusionLevel = 1.0
oldLighting = false
screen = <empty> <profile> *
sliders = MIST_AMOUNT PRISM_AMOUNT SHADOW_SOFT EXPOSURE CLOUD_COVER
