#version 330 compatibility
// Original Tidelume entry point; generated by tools/generate_programs.py.
#define WORLD_KIND -1
#define GEOM_ENTITY
#define GEOM_EMISSIVE
#define GEOM_TRANSLUCENT
#include "/program/geometry.fsh"
