#version 330 compatibility
// Original Tidelume entry point; generated by tools/generate_programs.py.
#define WORLD_KIND 0
#define GEOM_WATER
#define GEOM_TRANSLUCENT
#include "/program/geometry.vsh"
